# Generated by Django 2.0.1 on 2018-02-07 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0003_auto_20180207_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='news_blog.Author'),
        ),
    ]
