# Generated by Django 2.0.1 on 2018-02-07 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0005_auto_20180207_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.Author')),
            ],
        ),
    ]
